src/routes/_layout.svelte, src/routes/index.svelte, theme/_material-theme.scss
This is a new design for the website with a basic waiting list form. Still needs refinement.
=> New design

package-lock.json, package.json, rollup.config.js, src/routes/_layout.svelte, src/routes/index.svelte, tailwind.config.js
=> Add new api info on card, display image, import tailwind, yikes

src/components/Head.svelte, src/routes/index.svelte
Head allows us to easily customize the OpenGraph and Twitter tags for SEO
=> Introduce Head component

package-lock.json, package.json, src/routes/index.svelte
=> Typewriter

src/components/Footer.svelte, src/components/Link.svelte, src/routes/index.svelte
=> Issue/41 - Add more details about volunteering

src/components/Button.svelte, src/components/Card.svelte, src/routes/_layout.svelte, src/routes/home.svelte, src/routes/sign-in.svelte
=> Issue/56 - Consolidate duplicated CSS

functions/auth-code.js, src/routes/sign-in/code.svelte, src/routes/sign-in/index.svelte
=> Issue/48 - Introduce /sign-in/code page

src/routes/sign-in/index.svelte
=> Format phone number if longer than 6 chars

src/components/TextInput.svelte, src/routes/home/index.svelte, src/routes/home/thing.svelte, src/routes/sign-in/code.svelte, src/routes/sign-in/index.svelte, src/routes/sign-up.svelte
Proposed change: pull out all of our input elements into a component with styles and common features built in.
=> Issue/92 - TextInput component

src/components/Footer.svelte
=> Add insta SVG and link

src/components/Footer.svelte
=> Add facebook logo

src/routes/donations.svelte, src/routes/index.svelte
Updates the verbiage on the homepage, adds a donations page, and a link to a Google form. Also changed "member-owned" to "non-profit" where applicable.
=> Update verbiage and add page for donations

src/routes/donations.svelte
=> Make donation types less ambiguous

src/components/Layout.svelte, src/routes/_layout.svelte
This doesn't address the sign-in and code page design, but this at least fixes how the footer is positioned on every page of the site.
=> Push footer to bottom of Layout

src/components/Terminal.svelte, src/routes/index.svelte
Couldn't think of a better way other than moving the tagline out of the typewriter.
This solves issue #43
=> Fix typewriter overflow

src/components/Spanner.svelte, src/components/Subheading.svelte, src/routes/index.svelte
This is still in progress, but let me know what you think. See issue #124
=> Stats and verbiage

src/routes/donations.svelte, src/routes/index.svelte
I'd like to replace the Google form for donations with a new Airtable form.
=> Replace Google form with Airtable form

src/components/Scroller.svelte, src/routes/browse.svelte, src/routes/index.svelte
FYI: in order to test, you'll need to run the latest Things API code locally and modify the _things_ function in the app to point to your local Things API.
=> Connect to Airtable

src/routes/index.svelte
=> Add 3/4 width to page

src/components/Header.svelte
=> Add Back button to header

src/components/Header.svelte
=> Header and logo matches square site header

src/routes/index.svelte
=> Add wanted filter
